/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/epics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Epics */
        get: operations["list_epics_api_v1_projects__project_id__epics_get"];
        put?: never;
        /** Create Epic */
        post: operations["create_epic_api_v1_projects__project_id__epics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/epics/{epic_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Features */
        get: operations["list_features_api_v1_projects__project_id__epics__epic_id__features_get"];
        put?: never;
        /** Create Feature */
        post: operations["create_feature_api_v1_projects__project_id__epics__epic_id__features_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/features/{feature_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_projects__project_id__features__feature_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Task Dependency
         * @description Add a `blocked_by` edge between two tasks in the same project. Downstream task `task_id` will be rejected from `start_task` / `update_task_status(status="in_progress")` until the upstream task (`depends_on_id`) is resolved (done OR review with pr_url). Self-loops, cycles, and cross-project pairings return 400/409.
         */
        post: operations["add_task_dependency_api_v1_tasks__task_id__dependencies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/dependencies/{depends_on_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Task Dependency
         * @description Remove a `blocked_by` edge between two tasks.
         */
        delete: operations["remove_task_dependency_api_v1_tasks__task_id__dependencies__depends_on_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/epics/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Epics */
        post: operations["reorder_epics_api_v1_projects__project_id__epics_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/epics/{epic_id}/features/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Features */
        post: operations["reorder_features_api_v1_projects__project_id__epics__epic_id__features_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/tasks/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Tasks */
        post: operations["reorder_tasks_api_v1_features__feature_id__tasks_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Board */
        get: operations["get_board_api_v1_projects__project_id__board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backlog */
        get: operations["get_backlog_api_v1_projects__project_id__backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Plan */
        post: operations["import_plan_api_v1_projects__project_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Project Info
         * @description Return the project associated with the current API key.
         */
        get: operations["get_current_project_info_api_v1_gateway_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Stream real-time events for a project via SSE. Public endpoint.
         */
        get: operations["stream_events_api_v1_projects__project_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Agent
         * @description Register a worktree agent. Requires valid API key.
         */
        post: operations["register_agent_api_v1_agents_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_api_v1_agents__worktree_id__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tasks
         * @description Get all tasks assigned to this worktree.
         */
        get: operations["get_tasks_api_v1_agents__worktree_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/start-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Task */
        post: operations["start_task_api_v1_agents__worktree_id__start_task_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/complete-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task */
        post: operations["complete_task_api_v1_agents__worktree_id__complete_task_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/task-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task Status */
        patch: operations["update_task_status_api_v1_agents__worktree_id__task_status_patch"];
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/mark-pr-merged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Pr Merged */
        post: operations["mark_pr_merged_api_v1_agents__worktree_id__mark_pr_merged_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/unregister": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unregister Agent */
        post: operations["unregister_agent_api_v1_agents__worktree_id__unregister_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/request-shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Shutdown
         * @description T-218 — supervisor-initiated graceful shutdown. Writes a `shutdown`
         *     JSON line to `<worktree_path>/.cloglog/inbox`. Idempotent. Auth via
         *     MCP service key or project API key.
         */
        post: operations["request_shutdown_api_v1_agents__worktree_id__request_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{worktree_id}/force-unregister": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force Unregister
         * @description T-221 — tier-2 fallback for wedged worktrees. Ends the active
         *     session, deletes the worktree row, and emits a single
         *     `WORKTREE_OFFLINE` event with `reason: "force_unregistered"`.
         *     Idempotent: returns `already_unregistered: true` on repeat calls.
         *     Auth: MCP service key OR project API key (agent tokens are refused
         *     so a wedged agent cannot force-unregister itself).
         */
        post: operations["force_unregister_api_v1_agents__worktree_id__force_unregister_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/worktrees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Worktrees */
        get: operations["list_worktrees_api_v1_projects__project_id__worktrees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        /** Create Document */
        post: operations["create_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DependencyCreate
         * @description Request body for adding a dependency. Used by both the feature-dep routes (POST /features/{id}/dependencies) and the task-dep routes (POST /tasks/{id}/dependencies).
         */
        DependencyCreate: {
            /**
             * Depends On Id
             * Format: uuid
             */
            depends_on_id: string;
        };
        /** BacklogEpic */
        BacklogEpic: {
            epic: components["schemas"]["EpicResponse"];
            /** Features */
            features: components["schemas"]["BacklogFeature"][];
            task_counts: components["schemas"]["TaskCounts"];
        };
        /** BacklogFeature */
        BacklogFeature: {
            feature: components["schemas"]["FeatureResponse"];
            /** Tasks */
            tasks: components["schemas"]["BacklogTask"][];
            task_counts: components["schemas"]["TaskCounts"];
        };
        /** BacklogTask */
        BacklogTask: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
        };
        /** BoardColumn */
        BoardColumn: {
            /** Status */
            status: string;
            /** Tasks */
            tasks: components["schemas"]["TaskCard"][];
        };
        /** BoardResponse */
        BoardResponse: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Columns */
            columns: components["schemas"]["BoardColumn"][];
            /** Total Tasks */
            total_tasks: number;
            /** Done Count */
            done_count: number;
        };
        /** MarkPrMergedRequest */
        MarkPrMergedRequest: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** CompleteTaskRequest */
        CompleteTaskRequest: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** CompleteTaskResponse */
        CompleteTaskResponse: {
            /**
             * Completed Task Id
             * Format: uuid
             */
            completed_task_id: string;
            next_task?: components["schemas"]["TaskInfo"] | null;
        };
        /** DocumentCreate */
        DocumentCreate: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Doc Type
             * @default other
             */
            doc_type: string;
            /**
             * Source Path
             * @default
             */
            source_path: string;
            /**
             * Attached To Type
             * @default
             */
            attached_to_type: string;
            /** Attached To Id */
            attached_to_id?: string | null;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Doc Type */
            doc_type: string;
            /** Source Path */
            source_path: string;
            /** Attached To Type */
            attached_to_type: string;
            /** Attached To Id */
            attached_to_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EpicCreate */
        EpicCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Bounded Context
             * @default
             */
            bounded_context: string;
            /**
             * Context Description
             * @default
             */
            context_description: string;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /** EpicResponse */
        EpicResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Bounded Context */
            bounded_context: string;
            /** Context Description */
            context_description: string;
            /** Status */
            status: string;
            /** Position */
            position: number;
            /** Color */
            color: string;
            /** Number */
            number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeatureCreate */
        FeatureCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /** FeatureResponse */
        FeatureResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Epic Id
             * Format: uuid
             */
            epic_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Position */
            position: number;
            /** Number */
            number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ForceUnregisterResponse */
        ForceUnregisterResponse: {
            /**
             * Worktree Id
             * Format: uuid
             */
            worktree_id: string;
            /** Already Unregistered */
            already_unregistered: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatResponse */
        HeartbeatResponse: {
            /** Status */
            status: string;
            /**
             * Last Heartbeat
             * Format: date-time
             */
            last_heartbeat: string;
        };
        /** ImportEpic */
        ImportEpic: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Bounded Context
             * @default
             */
            bounded_context: string;
            /**
             * Features
             * @default []
             */
            features: components["schemas"]["ImportFeature"][];
        };
        /** ImportFeature */
        ImportFeature: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["ImportTask"][];
        };
        /** ImportPlan */
        ImportPlan: {
            /** Epics */
            epics: components["schemas"]["ImportEpic"][];
        };
        /** ImportTask */
        ImportTask: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Priority
             * @default normal
             */
            priority: string;
        };
        /** ReorderItem */
        ReorderItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
        };
        /** ReorderRequest */
        ReorderRequest: {
            /** Items */
            items: components["schemas"]["ReorderItem"][];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Repo Url
             * @default
             */
            repo_url: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string;
            /** Description */
            description?: string;
            /** Repo Url */
            repo_url?: string | null;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Repo Url */
            repo_url: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectWithKey */
        ProjectWithKey: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Repo Url */
            repo_url: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Api Key */
            api_key: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Worktree Path
             * @description Absolute path to the git worktree on the calling side's filesystem. Must be non-empty — downstream code derives the inbox path (``<worktree_path>/.cloglog/inbox``) from this value.
             */
            worktree_path: string;
            /**
             * Branch Name
             * @default
             */
            branch_name: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /**
             * Worktree Id
             * Format: uuid
             */
            worktree_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            current_task?: components["schemas"]["TaskInfo"] | null;
            /**
             * Resumed
             * @default false
             */
            resumed: boolean;
        };
        /** StartTaskRequest */
        StartTaskRequest: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** StartTaskResponse */
        StartTaskResponse: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Status */
            status: string;
            /** Model */
            model?: string | null;
        };
        /**
         * TaskCard
         * @description Task with breadcrumb info for the Kanban board.
         */
        TaskCard: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Feature Id
             * Format: uuid
             */
            feature_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
            /** Worktree Id */
            worktree_id: string | null;
            /** Position */
            position: number;
            /** Number */
            number: number;
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Epic Title
             * @default
             */
            epic_title: string;
            /**
             * Feature Title
             * @default
             */
            feature_title: string;
            /**
             * Epic Color
             * @default
             */
            epic_color: string;
            /** Pr Url */
            pr_url?: string | null;
            /**
             * Pr Merged
             * @default false
             */
            pr_merged: boolean;
            /**
             * Codex Review Picked Up
             * @description True when at least one codex review turn has been persisted
             *     for this task's pr_url. Drives the "codex reviewed" badge on
             *     review-column task cards (T-260). Projected read-only from
             *     ``pr_review_turns``; never a write target.
             * @default false
             */
            codex_review_picked_up: boolean;
            /** Model */
            model?: string | null;
        };
        /** TaskCounts */
        TaskCounts: {
            /** Total */
            total: number;
            /** Done */
            done: number;
        };
        /** TaskCreate */
        TaskCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Priority
             * @default normal
             */
            priority: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Model */
            model?: string | null;
        };
        /** TaskInfo */
        TaskInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
            /** Pr Url */
            pr_url?: string | null;
            /** Artifact Path */
            artifact_path?: string | null;
            /** Model */
            model?: string | null;
        };
        /** TaskResponse */
        TaskResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Feature Id
             * Format: uuid
             */
            feature_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
            /** Worktree Id */
            worktree_id: string | null;
            /** Position */
            position: number;
            /** Number */
            number: number;
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Model */
            model?: string | null;
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Priority */
            priority?: string | null;
            /** Worktree Id */
            worktree_id?: string | null;
            /** Position */
            position?: number | null;
            /** Archived */
            archived?: boolean | null;
            /** Model */
            model?: string | null;
        };
        /** UpdateTaskStatusRequest */
        UpdateTaskStatusRequest: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorktreeResponse */
        WorktreeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Name */
            name: string;
            /** Worktree Path */
            worktree_path: string;
            /** Branch Name */
            branch_name: string;
            /** Status */
            status: string;
            /** Current Task Id */
            current_task_id: string | null;
            /** Last Heartbeat */
            last_heartbeat: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWithKey"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_epics_api_v1_projects__project_id__epics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpicResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_epic_api_v1_projects__project_id__epics_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_features_api_v1_projects__project_id__epics__epic_id__features_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                epic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feature_api_v1_projects__project_id__epics__epic_id__features_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                epic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_projects__project_id__features__feature_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_task_dependency_api_v1_tasks__task_id__dependencies_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DependencyCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation error — self-loop, cross-project, or cycle */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_task_dependency_api_v1_tasks__task_id__dependencies__depends_on_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                depends_on_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed (no content) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task or dependency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_epics_api_v1_projects__project_id__epics_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_features_api_v1_projects__project_id__epics__epic_id__features_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                epic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_tasks_api_v1_features__feature_id__tasks_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_api_v1_projects__project_id__board_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backlog_api_v1_projects__project_id__backlog_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogEpic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_plan_api_v1_projects__project_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPlan"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_project_info_api_v1_gateway_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    stream_events_api_v1_projects__project_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_agent_api_v1_agents_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_api_v1_agents__worktree_id__heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tasks_api_v1_agents__worktree_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_task_api_v1_agents__worktree_id__start_task_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_task_api_v1_agents__worktree_id__complete_task_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_status_api_v1_agents__worktree_id__task_status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_pr_merged_api_v1_agents__worktree_id__mark_pr_merged_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkPrMergedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unregister_agent_api_v1_agents__worktree_id__unregister_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_shutdown_api_v1_agents__worktree_id__request_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        shutdown_requested: boolean;
                    };
                };
            };
            /** @description Worktree not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Worktree has no worktree_path (legacy row) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_unregister_api_v1_agents__worktree_id__force_unregister_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worktree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForceUnregisterResponse"];
                };
            };
            /** @description Worktree belongs to a different project */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_worktrees_api_v1_projects__project_id__worktrees_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorktreeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                attached_to_type?: string | null;
                attached_to_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
